using UnityEngine;
using TMPro;
using UnityEngine.UI;
using UnityEngine.SceneManagement;
using System.Collections;

public class FlashlightManager : MonoBehaviour
{
    [Header("Flashlight Settings")]
    public Sprite darkOverlayWithHole;
    public float overlaySize = 200f;

    [Header("ระบบเวลา (ลาก CountdownTimer มาใส่)")]
    public CountdownTimer matchTimer;

    [Header("ตั้งค่ารูปและข้อความ")]
    public Sprite winSprite;
    public Sprite loseSprite;
    public string winText = "ชนะแล้ว!";
    public string loseText = "พ่ายแพ้!";

    // ตัวแปร UI ที่โค้ดจะวิ่งหาเอง
    private GameObject winLosePanelObj;
    private Image winLoseImage;
    private TextMeshProUGUI endgameText;

    private GameObject flashlightOverlayObj;
    private bool isGameActive = false;
    private SceneHandle currentScene; // หรือ ZoneHandle ตามที่คุณใช้

    private void Start()
    {
        Time.timeScale = 1f; // 🌟 เคลียร์ค่า Pause ตอนเริ่มด่านใหม่เสมอ

        currentScene = FindObjectOfType<SceneHandle>();
        CreateFlashlightOverlay();
        isGameActive = true;


        if (matchTimer != null)
        {
            matchTimer.onTimeOut.AddListener(GameOver);
            matchTimer.StartTimer();
        }

        // 🌟 สั่งรันระบบค้นหา UI อัตโนมัติ
        StartCoroutine(FindAutoGeneratedUI());
    }

    // ==========================================
    // 🌟 ระบบงมหา UI (สแกนหาทุกซอกทุกมุม)
    // ==========================================
    private IEnumerator FindAutoGeneratedUI()
    {
        // หน่วงเวลาเผื่อ Core Manager โหลดของหนัก
        yield return new WaitForSeconds(0.5f);

        if (Gamemanager.Instance != null && Gamemanager.Instance.uiIngame != null && Gamemanager.Instance.uiIngame.panalgame != null)
        {
            // สแกนหา Transform ทั้งหมดใต้ panalgame (true = หาตัวที่ซ่อนอยู่ด้วย)
            Transform[] allUIElements = Gamemanager.Instance.uiIngame.panalgame.GetComponentsInChildren<Transform>(true);
            Transform winLoseTrans = null;

            // วนหาชื่อ win_lose
            foreach (Transform t in allUIElements)
            {
                if (t.name == "win_lose")
                {
                    winLoseTrans = t;
                    break;
                }
            }

            if (winLoseTrans != null)
            {
                winLosePanelObj = winLoseTrans.gameObject;
                winLoseImage = winLosePanelObj.GetComponent<Image>();
                winLosePanelObj.SetActive(false); // ซ่อนหน้าต่างไว้ตอนเล่นเกม

                // หา endgame_txt 
                Transform textTrans = winLoseTrans.Find("endgame_txt");
                if (textTrans != null) endgameText = textTrans.GetComponent<TextMeshProUGUI>();

                Debug.Log("✅ [FlashlightManager] ผูกหน้าต่าง win_lose!");
            }
            else
            {
                Debug.LogWarning("⚠️ [FlashlightManager] หา win_lose ไม่เจอ! ลองเช็คชื่อใน Hierarchy อีกครั้ง");
            }
        }
    }

    private void CreateFlashlightOverlay()
    {
        flashlightOverlayObj = new GameObject("Auto_FlashlightDarkness");
        SpriteRenderer renderer = flashlightOverlayObj.AddComponent<SpriteRenderer>();

        renderer.sprite = darkOverlayWithHole;
        renderer.sortingOrder = 900;
        renderer.drawMode = SpriteDrawMode.Sliced;
        renderer.size = new Vector2(overlaySize, overlaySize);
        flashlightOverlayObj.transform.localScale = Vector3.one;

        Cursor.visible = false;
    }

    private void Update()
    {
        if (!isGameActive || !Gamemanager.Instance.isStateGamePlay()) return;

        if (Camera.main != null && flashlightOverlayObj != null)
        {
            Vector3 mousePos = Camera.main.ScreenToWorldPoint(Input.mousePosition);
            mousePos.z = 0f;
            flashlightOverlayObj.transform.position = mousePos;
        }

        if (currentScene != null && currentScene.lostDogs.Count == 0)
        {
            GameWin();
        }
    }

    public void GameWin()
    {
        if (!isGameActive) return;
        isGameActive = false;
        Cursor.visible = true;
        if (matchTimer != null) matchTimer.StopTimer();


        // 🌟 เรียกใช้ UI ชนะ
        if (winLosePanelObj != null)
        {
            winLosePanelObj.SetActive(true);
            if (winLoseImage != null && winSprite != null) winLoseImage.sprite = winSprite;
            if (endgameText != null) endgameText.text = winText;
        }

        if (currentScene != null && Gamemanager.Instance != null)
        {
            Gamemanager.Instance.ClearScene(currentScene.sceneObject.name);
            if (Gamemanager.Instance.dialogueUIManager != null)
            {
                UIManager.Instance.ShowDialog("dialog_found_all");
            }
        }
    }

    public void GameOver()
    {
        if (!isGameActive) return;
        isGameActive = false;
        Cursor.visible = true;
        if (matchTimer != null) matchTimer.StopTimer();


        // 🌟 เรียกใช้ UI แพ้
        if (winLosePanelObj != null)
        {
            winLosePanelObj.SetActive(true);
            if (winLoseImage != null && loseSprite != null) winLoseImage.sprite = loseSprite;
            if (endgameText != null) endgameText.text = loseText;
        }

        //if (Gamemanager.Instance != null && Gamemanager.Instance.dialogueUIManager != null)
        //{
        //    UIManager.Instance.ShowDialog("dialog_lose");
        //}
    }

    private void OnDestroy()
    {
        if (flashlightOverlayObj != null) Destroy(flashlightOverlayObj);
        Cursor.visible = true;
    }
}